@baseUrl = http://localhost:3333
@authToken = {{login.response.body.$.access_token}}
@slug_store = {{list_stores.response.body.$[0].slug}}
@id_store = {{list_stores.response.body.$[0].id}}

# Health
GET {{baseUrl}}/health

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "jane.doe@example.com",
  "password": "123456"
}

###

# @name list_stores
GET {{baseUrl}}/store

###

# @name get_store_by_slug
GET {{baseUrl}}/store/{{slug_store}}

###

# @name create_store 
POST {{baseUrl}}/store
Content-Type: application/json

{
  "cnpj": "12.345.678/0001-90",
  "name": "The Corner Store",
  "responsibleName": "Jane Doe",
  "email": "jane.doe@example.com",
  "password": "123456",
  "confirmPassword": "123456",
  "phone": "11999998888",
  "address": {
    "zipCode": "61936180",
    "street": "Rua 118",
    "number": "100",
    "district": "Timbó",
    "city": "Maracanaú",
    "state": "CE",
    "complement": ""
  }
}

###

# @name update_store
PUT {{baseUrl}}/store
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "The Corner Store",
  "responsibleName": "Jane Doe",
  "email": "jane.doe@example.com",
  "phone": "11999998888",
  "address": {
    "zipCode": "61936180",
    "street": "Rua 118",
    "number": "100",
    "district": "Timbó",
    "city": "Maracanaú",
    "state": "CE",
    "complement": ""
  }
}

###

# # @name active_store
# PATCH {{baseUrl}}/store
# Authorization: Bearer {{authToken}}
# Content-Type: application/json

###

# @name delete_store
DELETE {{baseUrl}}/store
Authorization: Bearer {{authToken}}

###

# @name create_products
POST {{baseUrl}}/store/{{slug_store}}/product
Authorization: Bearer {{authToken}}
Content-Type: application/json

[
  {
    "title": "leite da manha",
    "description": "Pão carioquinha com ovo, queijo e presunto",
    "price": 4.99,
    "imageUrl": "http://cafe-da-manha.com",
    "stoque": false,
    "amount": 0
  },
  {
    "title": "leite da tarde",
    "description": "Pão carioquinha com ovo, queijo e presunto",
    "price": 4.99,
    "imageUrl": "http://cafe-da-manha.com",
    "stoque": false,
    "amount": 0
  }
]

###

# @name list_products
GET {{baseUrl}}/store/{{slug_store}}/product

###

# @name update_product
PUT {{baseUrl}}/product
Authorization: Bearer {{authToken}}
Content-Type: application/json