@baseUrl = http://localhost:3333
@authToken = {{login.response.body.$.access_token}}
@slug_store = {{list_stores.response.body.$[0].slug}}
@id_store = {{list_stores.response.body.$[0].id}}
@id_product1 = {{list_products.response.body.$[0].id}}
@id_product2 = {{list_products.response.body.$[1].id}}
@id_client = {{list_clients.response.body.$[0].id}}
@id_order = {{list_orders.response.body.$[0].id}}

# Health
GET {{baseUrl}}/health

###

# STORES

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "jane.doe1@example.com",
  "password": "123456"
}

###

# @name list_stores
GET {{baseUrl}}/store

###

# @name get_store_by_slug
GET {{baseUrl}}/store/{{slug_store}}
Content-Type: application/json

###

# @name create_store
POST {{baseUrl}}/store
Content-Type: application/json

{
  "cnpj": "12.345.678/0001-91",
  "name": "The storee",
  "responsibleName": "Jane Doe",
  "email": "jane.doe1@example.com",
  "password": "123456",
  "confirmPassword": "123456",
  "phone": "11999998888",
  "address": {
    "zipCode": "61936180",
    "street": "Rua 118",
    "number": "100",
    "district": "Timbó",
    "city": "Maracanaú",
    "state": "CE",
    "complement": ""
  }
}

###

# @name update_store
PUT {{baseUrl}}/store
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "The Corner Store",
  "responsibleName": "Jane Doe",
  "email": "jane.doe@example.com",
  "phone": "11999998888",
  "address": {
    "zipCode": "61936180",
    "street": "Rua 118",
    "number": "100",
    "district": "Timbó",
    "city": "Maracanaú",
    "state": "CE",
    "complement": ""
  }
}

###

# @name delete_store
DELETE {{baseUrl}}/store
Authorization: Bearer {{authToken}}

###

# PRODUCTS

# @name create_products
POST {{baseUrl}}/store/{{slug_store}}/product
Authorization: Bearer {{authToken}}
Content-Type: application/json

[
  {
    "title": "Arroz",
    "description": "alimentos",
    "price": 4.99,
    "imageUrl": "http://cafe-da-manha.com",
    "stock": true,
    "amount": 500
  },
  {
    "title": "Feijao",
    "description": "alimentos",
    "price": 4.99,
    "imageUrl": "http://cafe-da-manha.com",
    "stock": true,
    "amount": 450
  }
]

###

# @name list_products
GET {{baseUrl}}/store/{{slug_store}}/product

###

# @name update_product
PUT {{baseUrl}}/store/{{slug_store}}/product
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": "4686a089-3f99-4d89-b36e-390ced4d30c0",
  "title": "Café da manhã de novo",
  "description": "Cafézinho",
  "price": 4.98,
  "stock": true,
  "amount": 0,
  "imageUrl": "http://cafe-da-manha.com",
  "storeId": "02f56094-9ab7-4d03-8867-893ba060894c",
  "slug": "cafe-da-manha-de-"
}

###

# @name delete_product
DELETE {{baseUrl}}/store/{{slug_store}}/product/{{id_product1}}
Authorization: Bearer {{authToken}}

###

# CLIENTS

# @name create_client
POST {{baseUrl}}/client/
Content-Type: application/json

{
 "name": "Jane Doe",
 "phone": "11999998888",
 "zipCode": "61936180",
 "street": "Rua 118",
 "number": "100",
 "district": "Timbó",
 "city": "Maracanaú",
 "state": "CE",
 "complement": ""
}
  

###

# @name list_clients
GET {{baseUrl}}/client

###

# @name update_client
PUT {{baseUrl}}/client/{{id_client}}
Content-Type: application/json

{
  "name": "Jane Doe",
  "phone": "11999998883",
  "zipCode": "61936180",
  "street": "Rua 118",
  "number": "100",
  "district": "Timbó",
  "city": "Maracanaú",
  "state": "CE",
  "complement": ""
}

###

# @name delete_client
DELETE {{baseUrl}}/client/{{id_client}}

###

# ORDERS

# @name create_order
POST {{baseUrl}}/store/{{slug_store}}/order
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "clientId": "{{id_client}}",
  "storeId": "{{id_store}}",
  "products": [
    {
      "id": "{{id_product1}}",
      "amount": 2
    },
    {
      "id": "{{id_product2}}",
      "amount": 4
    }
  ]
}

###

# @name list_orders
GET {{baseUrl}}/store/{{slug_store}}/order
Authorization: Bearer {{authToken}}

###

# @name get_order_by_id
GET {{baseUrl}}/store/{{slug_store}}/order/{{create_order.response.body.$.orderId}}
Authorization: Bearer {{authToken}}

###

# @name update_order
PUT {{baseUrl}}/store/{{slug_store}}/order
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id": "{{create_order.response.body.$.orderId}}",
  "status": "ATTENDING"
}

###

# @name cancel_order
PUT {{baseUrl}}/store/{{slug_store}}/order
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id": "{{create_order.response.body.$.orderId}}",
  "status": "CANCELED",
  "reason": "Client requested cancellation"
}

###

# @name delete_order
DELETE {{baseUrl}}/store/{{slug_store}}/order/{{create_order.response.body.$.orderId}}
Authorization: Bearer {{authToken}}
